name: Storefront 1000047427

on:
  workflow_dispatch:        # allow manual run
  push:                     # run on pushes to main
    branches: [main]

permissions:
  contents: write           # needed for Git actions within deploy
  deployments: write

jobs:
  deploy:
    name: Deploy to Oxygen
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git for CI
        run: |
          git config --global user.name "Flying Circus Bot"
          git config --global user.email "bot@flyingcircuscoffee.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true

      - name: Cache Node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ run
